repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-yaml
    - id: double-quote-string-fixer
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: detect-private-key
-   repo: local
    hooks:
    -   id: secretlint
        name: secretlint
        language: node
        entry: npx secretlint
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: script-must-have-extension
  - id: git-check
  - id: forbid-binary
